"""us1 data source and domain schema

Revision ID: a48910eab2cb
Revises: d8607cfff4ac
Create Date: 2026-09-10 13:49:03.220316
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.migrations import attach_append_only, detach_append_only

revision: str = 'a48910eab2cb'
down_revision: str | None = 'd8607cfff4ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OBSERVABILITY_TABLES = (
    "item",
    "warehouse",
    "supplier",
    "stock_level",
    "item_supplier",
    "price",
    "lead_time",
    "purchase_order",
    "consumption",
    "production_demand",
    "quality_record",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'sku', name='uq_item_enterprise_sku')
    )
    op.create_index(op.f('ix_item_enterprise_id'), 'item', ['enterprise_id'], unique=False)
    op.create_table('supplier',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'code', name='uq_supplier_enterprise_code')
    )
    op.create_index(op.f('ix_supplier_enterprise_id'), 'supplier', ['enterprise_id'], unique=False)
    op.create_table('warehouse',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'code', name='uq_warehouse_enterprise_code')
    )
    op.create_index(op.f('ix_warehouse_enterprise_id'), 'warehouse', ['enterprise_id'], unique=False)
    op.create_table('consumption',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_enterprise_id'), 'consumption', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_consumption_item_id'), 'consumption', ['item_id'], unique=False)
    op.create_index(op.f('ix_consumption_warehouse_id'), 'consumption', ['warehouse_id'], unique=False)
    op.create_table('data_source',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('connector_type', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_ref', sa.UUID(), nullable=True),
    sa.Column('observation_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credential_ref'], ['secret.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_enterprise_id'), 'data_source', ['enterprise_id'], unique=False)
    op.create_table('item_supplier',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_supplier_enterprise_id'), 'item_supplier', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_item_supplier_item_id'), 'item_supplier', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_supplier_supplier_id'), 'item_supplier', ['supplier_id'], unique=False)
    op.create_table('lead_time',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_time_enterprise_id'), 'lead_time', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_lead_time_item_id'), 'lead_time', ['item_id'], unique=False)
    op.create_index(op.f('ix_lead_time_supplier_id'), 'lead_time', ['supplier_id'], unique=False)
    op.create_table('price',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_enterprise_id'), 'price', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_price_item_id'), 'price', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_supplier_id'), 'price', ['supplier_id'], unique=False)
    op.create_table('production_demand',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('need_by', sa.Date(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_demand_enterprise_id'), 'production_demand', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_production_demand_item_id'), 'production_demand', ['item_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('procurement_action_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'external_ref', name='uq_po_enterprise_external_ref')
    )
    op.create_index(op.f('ix_purchase_order_enterprise_id'), 'purchase_order', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_item_id'), 'purchase_order', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_supplier_id'), 'purchase_order', ['supplier_id'], unique=False)
    op.create_table('quality_record',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('defect_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_record_enterprise_id'), 'quality_record', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_quality_record_item_id'), 'quality_record', ['item_id'], unique=False)
    op.create_index(op.f('ix_quality_record_supplier_id'), 'quality_record', ['supplier_id'], unique=False)
    op.create_table('stock_level',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_level_enterprise_id'), 'stock_level', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_stock_level_item_id'), 'stock_level', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_level_warehouse_id'), 'stock_level', ['warehouse_id'], unique=False)
    op.create_table('field_mapping',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('source_field_path', sa.String(), nullable=False),
    sa.Column('canonical_entity', sa.String(), nullable=False),
    sa.Column('canonical_attribute', sa.String(), nullable=False),
    sa.Column('transform', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mapping_data_source_id'), 'field_mapping', ['data_source_id'], unique=False)
    op.create_table('source_field',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('inferred_type', sa.String(), nullable=False),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'path', name='uq_source_field_source_path')
    )
    op.create_index(op.f('ix_source_field_data_source_id'), 'source_field', ['data_source_id'], unique=False)
    op.create_table('mapping_change_event',
    sa.Column('field_mapping_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_mapping_id'], ['field_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_change_event_field_mapping_id'), 'mapping_change_event', ['field_mapping_id'], unique=False)
    # ### end Alembic commands ###

    # --- enum CHECK constraints (portable alternative to native enums; data-model.md §"Conventions") ---
    op.create_check_constraint(
        "ck_kind",
        "data_source",
        "kind IN ('erp', 'mes', 'wms', 'db', 'api', 'file', 'other')",
    )
    op.create_check_constraint(
        "ck_connector_type", "data_source", "connector_type IN ('rest', 'file', 'sql')"
    )
    op.create_check_constraint(
        "ck_health", "data_source", "health IN ('available', 'unavailable', 'stale')"
    )
    op.create_check_constraint(
        "ck_canonical_entity",
        "field_mapping",
        "canonical_entity IN ('item', 'warehouse', 'stock_level', 'supplier', 'item_supplier', "
        "'price', 'lead_time', 'purchase_order', 'consumption', 'production_demand', 'quality_record')",
    )
    op.create_check_constraint(
        "ck_status",
        "field_mapping",
        "status IN ('suggested', 'confirmed', 'rejected', 'retired')",
    )
    op.create_check_constraint(
        "ck_action",
        "mapping_change_event",
        "action IN ('suggested', 'confirmed', 'edited', 'rejected', 'retired')",
    )
    op.create_check_constraint(
        "ck_status", "purchase_order", "status IN ('open', 'received', 'cancelled')"
    )
    op.create_check_constraint(
        "ck_origin", "purchase_order", "origin IN ('external', 'smart_procurement')"
    )
    for table in _OBSERVABILITY_TABLES:
        op.create_check_constraint(
            "ck_observability", table, "observability IN ('fresh', 'stale', 'lost')"
        )

    # mapping_change_event is append-only (T027 / T044)
    attach_append_only("mapping_change_event")


def downgrade() -> None:
    detach_append_only("mapping_change_event")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_change_event_field_mapping_id'), table_name='mapping_change_event')
    op.drop_table('mapping_change_event')
    op.drop_index(op.f('ix_source_field_data_source_id'), table_name='source_field')
    op.drop_table('source_field')
    op.drop_index(op.f('ix_field_mapping_data_source_id'), table_name='field_mapping')
    op.drop_table('field_mapping')
    op.drop_index(op.f('ix_stock_level_warehouse_id'), table_name='stock_level')
    op.drop_index(op.f('ix_stock_level_item_id'), table_name='stock_level')
    op.drop_index(op.f('ix_stock_level_enterprise_id'), table_name='stock_level')
    op.drop_table('stock_level')
    op.drop_index(op.f('ix_quality_record_supplier_id'), table_name='quality_record')
    op.drop_index(op.f('ix_quality_record_item_id'), table_name='quality_record')
    op.drop_index(op.f('ix_quality_record_enterprise_id'), table_name='quality_record')
    op.drop_table('quality_record')
    op.drop_index(op.f('ix_purchase_order_supplier_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_item_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_enterprise_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_production_demand_item_id'), table_name='production_demand')
    op.drop_index(op.f('ix_production_demand_enterprise_id'), table_name='production_demand')
    op.drop_table('production_demand')
    op.drop_index(op.f('ix_price_supplier_id'), table_name='price')
    op.drop_index(op.f('ix_price_item_id'), table_name='price')
    op.drop_index(op.f('ix_price_enterprise_id'), table_name='price')
    op.drop_table('price')
    op.drop_index(op.f('ix_lead_time_supplier_id'), table_name='lead_time')
    op.drop_index(op.f('ix_lead_time_item_id'), table_name='lead_time')
    op.drop_index(op.f('ix_lead_time_enterprise_id'), table_name='lead_time')
    op.drop_table('lead_time')
    op.drop_index(op.f('ix_item_supplier_supplier_id'), table_name='item_supplier')
    op.drop_index(op.f('ix_item_supplier_item_id'), table_name='item_supplier')
    op.drop_index(op.f('ix_item_supplier_enterprise_id'), table_name='item_supplier')
    op.drop_table('item_supplier')
    op.drop_index(op.f('ix_data_source_enterprise_id'), table_name='data_source')
    op.drop_table('data_source')
    op.drop_index(op.f('ix_consumption_warehouse_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_item_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_enterprise_id'), table_name='consumption')
    op.drop_table('consumption')
    op.drop_index(op.f('ix_warehouse_enterprise_id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_supplier_enterprise_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_item_enterprise_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
