"""enum check constraints

Revision ID: a6db370213ce
Revises: e86718091d04
Create Date: 2026-09-07 11:39:52.701182
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "a6db370213ce"
down_revision: str | None = "e86718091d04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_event_type",
        "audit_record",
        "event_type IN ('recommendation', 'l4_prepared', 'l4_approved', 'l4_rejected', 'l5_authorized', 'dispatched', 'execution_result', 'verification', 'promotion', 'demotion', 'recovery', 'ai_unavailable', 'policy_approved', 'policy_revoked', 'mapping_confirmed', 'enforcement')",
    )
    op.create_check_constraint(
        "ck_verified",
        "audit_record",
        "verified IN ('verified', 'failed', 'unverifiable', 'pending', 'n/a')",
    )
    op.create_check_constraint(
        "ck_key",
        "capability",
        "key IN ('proc.inventory.observe', 'proc.demand.observe', 'proc.risk.diagnose', 'proc.order.recommend', 'proc.po.create', 'proc.replenish.routine', 'proc.supplier.add', 'proc.payment.release')",
    )
    op.create_check_constraint(
        "ck_level", "capability", "level IN ('L0', 'L1', 'L2', 'L3', 'L4', 'L5')"
    )
    op.create_check_constraint(
        "ck_direction", "capability_level_event", "direction IN ('promotion', 'demotion')"
    )
    op.create_check_constraint(
        "ck_from_level",
        "capability_level_event",
        "from_level IN ('L0', 'L1', 'L2', 'L3', 'L4', 'L5')",
    )
    op.create_check_constraint(
        "ck_to_level", "capability_level_event", "to_level IN ('L0', 'L1', 'L2', 'L3', 'L4', 'L5')"
    )
    op.create_check_constraint(
        "ck_trigger",
        "capability_level_event",
        "trigger IN ('human', 'incident', 'rollback', 'verification_failure', 'observability_loss', 'uncertainty', 'policy_expiry', 'policy_revocation')",
    )
    op.create_check_constraint(
        "ck_active_execution_adapter",
        "enterprise",
        "active_execution_adapter IN ('simulated', 'generic_rest')",
    )
    op.create_check_constraint(
        "ck_status", "job", "status IN ('pending', 'running', 'done', 'failed')"
    )
    op.create_check_constraint(
        "ck_reason",
        "observability_gap",
        "reason IN ('source_unavailable', 'stale_data', 'ai_unavailable')",
    )
    op.create_check_constraint(
        "ck_scope", "observability_gap", "scope IN ('source', 'entity', 'capability')"
    )
    op.create_check_constraint("ck_origin", "promotion_request", "origin IN ('human', 'ai')")
    op.create_check_constraint(
        "ck_proposed_to_level",
        "promotion_request",
        "proposed_to_level IN ('L0', 'L1', 'L2', 'L3', 'L4', 'L5')",
    )
    op.create_check_constraint(
        "ck_status", "promotion_request", "status IN ('pending', 'approved', 'rejected')"
    )
    op.create_check_constraint(
        "ck_purpose", "secret", "purpose IN ('source_credential', 'execution_endpoint')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_purpose", "secret", type_="check")
    op.drop_constraint("ck_status", "promotion_request", type_="check")
    op.drop_constraint("ck_proposed_to_level", "promotion_request", type_="check")
    op.drop_constraint("ck_origin", "promotion_request", type_="check")
    op.drop_constraint("ck_scope", "observability_gap", type_="check")
    op.drop_constraint("ck_reason", "observability_gap", type_="check")
    op.drop_constraint("ck_status", "job", type_="check")
    op.drop_constraint("ck_active_execution_adapter", "enterprise", type_="check")
    op.drop_constraint("ck_trigger", "capability_level_event", type_="check")
    op.drop_constraint("ck_to_level", "capability_level_event", type_="check")
    op.drop_constraint("ck_from_level", "capability_level_event", type_="check")
    op.drop_constraint("ck_direction", "capability_level_event", type_="check")
    op.drop_constraint("ck_level", "capability", type_="check")
    op.drop_constraint("ck_key", "capability", type_="check")
    op.drop_constraint("ck_verified", "audit_record", type_="check")
    op.drop_constraint("ck_event_type", "audit_record", type_="check")
    # ### end Alembic commands ###
