"""foundational schema

Revision ID: e86718091d04
Revises:
Create Date: 2026-09-07 11:39:51.605378
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e86718091d04"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enterprise",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("active_execution_adapter", sa.String(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("enterprise_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_enterprise_id"), "job", ["enterprise_id"], unique=False)
    op.create_index(op.f("ix_job_kind"), "job", ["kind"], unique=False)
    op.create_index(op.f("ix_job_run_at"), "job", ["run_at"], unique=False)
    op.create_table(
        "permission",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "audit_record",
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=True),
        sa.Column("capability_key", sa.String(), nullable=True),
        sa.Column("lorm_level", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("authorizer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("procurement_action_id", sa.UUID(), nullable=True),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("verified", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_record_at"), "audit_record", ["at"], unique=False)
    op.create_index(
        op.f("ix_audit_record_capability_key"), "audit_record", ["capability_key"], unique=False
    )
    op.create_index(
        op.f("ix_audit_record_correlation_id"), "audit_record", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_record_enterprise_id"), "audit_record", ["enterprise_id"], unique=False
    )
    op.create_table(
        "capability",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("l5_allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_tolerances", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("uncertainty_threshold", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enterprise_id", "key", name="uq_capability_enterprise_key"),
    )
    op.create_index(
        op.f("ix_capability_enterprise_id"), "capability", ["enterprise_id"], unique=False
    )
    op.create_table(
        "observability_gap",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("scope_ref", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observability_gap_enterprise_id"),
        "observability_gap",
        ["enterprise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observability_gap_scope_ref"), "observability_gap", ["scope_ref"], unique=False
    )
    op.create_table(
        "role",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enterprise_id", "key", name="uq_role_enterprise_key"),
    )
    op.create_index(op.f("ix_role_enterprise_id"), "role", ["enterprise_id"], unique=False)
    op.create_table(
        "secret",
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_secret_enterprise_id"), "secret", ["enterprise_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enterprise_id", "email", name="uq_user_enterprise_email"),
    )
    op.create_index(op.f("ix_user_enterprise_id"), "user", ["enterprise_id"], unique=False)
    op.create_table(
        "capability_level_event",
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("from_level", sa.String(), nullable=False),
        sa.Column("to_level", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["capability_id"], ["capability.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capability_level_event_capability_id"),
        "capability_level_event",
        ["capability_id"],
        unique=False,
    )
    op.create_table(
        "promotion_request",
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.Column("proposed_to_level", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["capability_id"], ["capability.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotion_request_capability_id"),
        "promotion_request",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotion_request_enterprise_id"),
        "promotion_request",
        ["enterprise_id"],
        unique=False,
    )
    op.create_table(
        "refresh_token",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_promotion_request_enterprise_id"), table_name="promotion_request")
    op.drop_index(op.f("ix_promotion_request_capability_id"), table_name="promotion_request")
    op.drop_table("promotion_request")
    op.drop_index(
        op.f("ix_capability_level_event_capability_id"), table_name="capability_level_event"
    )
    op.drop_table("capability_level_event")
    op.drop_index(op.f("ix_user_enterprise_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_secret_enterprise_id"), table_name="secret")
    op.drop_table("secret")
    op.drop_index(op.f("ix_role_enterprise_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_observability_gap_scope_ref"), table_name="observability_gap")
    op.drop_index(op.f("ix_observability_gap_enterprise_id"), table_name="observability_gap")
    op.drop_table("observability_gap")
    op.drop_index(op.f("ix_capability_enterprise_id"), table_name="capability")
    op.drop_table("capability")
    op.drop_index(op.f("ix_audit_record_enterprise_id"), table_name="audit_record")
    op.drop_index(op.f("ix_audit_record_correlation_id"), table_name="audit_record")
    op.drop_index(op.f("ix_audit_record_capability_key"), table_name="audit_record")
    op.drop_index(op.f("ix_audit_record_at"), table_name="audit_record")
    op.drop_table("audit_record")
    op.drop_table("permission")
    op.drop_index(op.f("ix_job_run_at"), table_name="job")
    op.drop_index(op.f("ix_job_kind"), table_name="job")
    op.drop_index(op.f("ix_job_enterprise_id"), table_name="job")
    op.drop_table("job")
    op.drop_table("enterprise")
    # ### end Alembic commands ###
