"""phase4 observation and analysis schema

T065 (observation_signal, sku_aggregate) + T069 (risk_finding incl. dismissal fields,
risk_signal_link, explanation), plus the audit_record.event_type CHECK constraint extension
for the new ``risk_dismissed`` event (Phase 4 decision #2). ``observation_signal`` is a normal
indexed table — deliberately **not** physically partitioned (data-model.md §4 v1 decision).

Revision ID: ee988845269c
Revises: a48910eab2cb
Create Date: 2026-09-22 14:57:10.219674
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.migrations import attach_append_only, detach_append_only

revision: str = "ee988845269c"
down_revision: str | None = "a48910eab2cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_EVENT_TYPES = (
    "recommendation",
    "l4_prepared",
    "l4_approved",
    "l4_rejected",
    "l5_authorized",
    "dispatched",
    "execution_result",
    "verification",
    "promotion",
    "demotion",
    "recovery",
    "ai_unavailable",
    "policy_approved",
    "policy_revoked",
    "mapping_confirmed",
    "enforcement",
)
_NEW_EVENT_TYPES = (*_OLD_EVENT_TYPES, "risk_dismissed")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "explanation",
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("what", sa.String(), nullable=False),
        sa.Column("why", sa.String(), nullable=False),
        sa.Column("data_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("generated_by", sa.String(), nullable=False),
        sa.Column("llm_provider", sa.String(), nullable=True),
        sa.Column("llm_model", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_explanation_enterprise_id"), "explanation", ["enterprise_id"], unique=False
    )
    op.create_index(op.f("ix_explanation_subject_id"), "explanation", ["subject_id"], unique=False)
    op.create_table(
        "risk_finding",
        sa.Column("risk_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("detected_by", sa.String(), nullable=False),
        sa.Column("ai_status", sa.String(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_reason", sa.String(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["dismissed_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_finding_enterprise_id"), "risk_finding", ["enterprise_id"], unique=False
    )
    op.create_index(op.f("ix_risk_finding_item_id"), "risk_finding", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_risk_finding_supplier_id"), "risk_finding", ["supplier_id"], unique=False
    )
    op.create_table(
        "sku_aggregate",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=True),
        sa.Column("avg_daily_consumption", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("days_of_cover", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("next_expected_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("price_trend", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("avg_supplier_delay_days", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouse.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "warehouse_id", name="uq_sku_aggregate_item_warehouse"),
    )
    op.create_index(
        op.f("ix_sku_aggregate_enterprise_id"), "sku_aggregate", ["enterprise_id"], unique=False
    )
    op.create_index(op.f("ix_sku_aggregate_item_id"), "sku_aggregate", ["item_id"], unique=False)
    op.create_table(
        "observation_signal",
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("signal_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("enterprise_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observation_signal_enterprise_id"),
        "observation_signal",
        ["enterprise_id"],
        unique=False,
    )
    op.create_index(
        "ix_observation_signal_enterprise_item_observed",
        "observation_signal",
        ["enterprise_id", "item_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_observation_signal_enterprise_supplier_observed",
        "observation_signal",
        ["enterprise_id", "supplier_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_observation_signal_enterprise_type_observed",
        "observation_signal",
        ["enterprise_id", "signal_type", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_signal_item_id"), "observation_signal", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_signal_observed_at"),
        "observation_signal",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_signal_supplier_id"),
        "observation_signal",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "risk_signal_link",
        sa.Column("risk_finding_id", sa.UUID(), nullable=False),
        sa.Column("observation_signal_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_signal_id"], ["observation_signal.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["risk_finding_id"], ["risk_finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_signal_link_observation_signal_id"),
        "risk_signal_link",
        ["observation_signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_signal_link_risk_finding_id"),
        "risk_signal_link",
        ["risk_finding_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- enum CHECK constraints (portable alternative to native enums) ---
    op.create_check_constraint(
        "ck_subject_type", "explanation", "subject_type IN ('risk_finding', 'recommendation')"
    )
    op.create_check_constraint("ck_generated_by", "explanation", "generated_by IN ('ai', 'rule')")
    op.create_check_constraint(
        "ck_risk_type",
        "risk_finding",
        "risk_type IN ('likely_shortage', 'insufficient_until_next_delivery', "
        "'production_stop_risk', 'systematic_supplier_delay', 'quality_degradation', "
        "'price_anomaly')",
    )
    op.create_check_constraint("ck_severity", "risk_finding", "severity IN ('low', 'med', 'high')")
    op.create_check_constraint(
        "ck_status",
        "risk_finding",
        "status IN ('open', 'recommended', 'actioned', 'resolved', 'dismissed')",
    )
    op.create_check_constraint("ck_detected_by", "risk_finding", "detected_by IN ('rule')")
    op.create_check_constraint(
        "ck_ai_status", "risk_finding", "ai_status IN ('pending', 'ready', 'unavailable')"
    )
    op.create_check_constraint(
        "ck_signal_type",
        "observation_signal",
        "signal_type IN ('stock_change', 'consumption_rate', 'reorder_point_near', "
        "'demand_change', 'supplier_delay', 'lead_time_change', 'price_change', "
        "'quality_issue', 'other')",
    )

    # observation_signal is append-only (T027 pattern; data-model.md §4/§8)
    attach_append_only("observation_signal")

    # Phase 4 decision #2: extend audit_record.event_type with 'risk_dismissed'.
    op.drop_constraint("ck_event_type", "audit_record", type_="check")
    op.create_check_constraint(
        "ck_event_type",
        "audit_record",
        "event_type IN (" + ", ".join(f"'{v}'" for v in _NEW_EVENT_TYPES) + ")",
    )


def downgrade() -> None:
    # Phase 4 decision #2: revert audit_record.event_type to its pre-Phase-4 value set.
    op.drop_constraint("ck_event_type", "audit_record", type_="check")
    op.create_check_constraint(
        "ck_event_type",
        "audit_record",
        "event_type IN (" + ", ".join(f"'{v}'" for v in _OLD_EVENT_TYPES) + ")",
    )

    detach_append_only("observation_signal")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_signal_link_risk_finding_id"), table_name="risk_signal_link")
    op.drop_index(op.f("ix_risk_signal_link_observation_signal_id"), table_name="risk_signal_link")
    op.drop_table("risk_signal_link")
    op.drop_index(op.f("ix_observation_signal_supplier_id"), table_name="observation_signal")
    op.drop_index(op.f("ix_observation_signal_observed_at"), table_name="observation_signal")
    op.drop_index(op.f("ix_observation_signal_item_id"), table_name="observation_signal")
    op.drop_index("ix_observation_signal_enterprise_type_observed", table_name="observation_signal")
    op.drop_index(
        "ix_observation_signal_enterprise_supplier_observed", table_name="observation_signal"
    )
    op.drop_index("ix_observation_signal_enterprise_item_observed", table_name="observation_signal")
    op.drop_index(op.f("ix_observation_signal_enterprise_id"), table_name="observation_signal")
    op.drop_table("observation_signal")
    op.drop_index(op.f("ix_sku_aggregate_item_id"), table_name="sku_aggregate")
    op.drop_index(op.f("ix_sku_aggregate_enterprise_id"), table_name="sku_aggregate")
    op.drop_table("sku_aggregate")
    op.drop_index(op.f("ix_risk_finding_supplier_id"), table_name="risk_finding")
    op.drop_index(op.f("ix_risk_finding_item_id"), table_name="risk_finding")
    op.drop_index(op.f("ix_risk_finding_enterprise_id"), table_name="risk_finding")
    op.drop_table("risk_finding")
    op.drop_index(op.f("ix_explanation_subject_id"), table_name="explanation")
    op.drop_index(op.f("ix_explanation_enterprise_id"), table_name="explanation")
    op.drop_table("explanation")
    # ### end Alembic commands ###
